# Enterprise RAG Chatbot Configuration

# Application Settings
app:
  name: "Enterprise RAG Chatbot"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3000"
    - "https://yourdomain.com"
  rate_limit:
    requests_per_minute: 60
    burst_size: 10

# Database Configuration
database:
  url: "${DATABASE_URL}"
  pool_size: 10
  max_overflow: 20
  echo: false

# Vector Database Configuration
vector_db:
  provider: "chroma"  # Options: chroma, pinecone, weaviate
  url: "${VECTOR_DB_URL}"
  collection_name: "rag_documents"
  embedding_dimension: 1536

# LLM Configuration
llm:
  primary_provider: "openai"
  fallback_providers: ["anthropic", "azure_openai"]
  models:
    openai:
      model: "gpt-4-turbo-preview"
      temperature: 0.1
      max_tokens: 2048
    anthropic:
      model: "claude-3-opus-20240229"
      temperature: 0.1
      max_tokens: 2048
  timeout: 30

# Embedding Configuration
embeddings:
  provider: "openai"
  model: "text-embedding-3-large"
  dimension: 1536
  batch_size: 100

# Memory Configuration
memory:
  provider: "redis"
  url: "${REDIS_URL}"
  session_ttl: 3600  # 1 hour
  cache_ttl: 1800    # 30 minutes

# Ingestion Configuration
ingestion:
  supported_formats: ["pdf", "docx", "txt", "md", "html"]
  chunk_size: 1000
  chunk_overlap: 200
  max_file_size: 10485760  # 10MB

# Retrieval Configuration
retrieval:
  top_k: 10
  similarity_threshold: 0.7
  hybrid_search:
    enabled: true
    vector_weight: 0.7
    keyword_weight: 0.3

# Guardrails Configuration
guardrails:
  content_filtering:
    enabled: true
    blocked_categories: ["hate", "violence", "sexual", "self-harm"]
  bias_detection:
    enabled: true
    threshold: 0.8
  safety_checks:
    enabled: true

# Monitoring Configuration
monitoring:
  metrics_enabled: true
  tracing_enabled: true
  health_check_interval: 30

# Security Configuration
security:
  api_key_header: "X-API-Key"
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry: 3600
  cors_enabled: true